spring.application.name=UserService
jwt.secret.key = ndjkehfyurgtyfbdjkcjwlhfkjrbggkjrhaxzeasrwcqcwqrjmlhjgwhfbq2132546358746894750860

server.port=9020
spring.datasource.url=jdbc:postgresql://localhost:5433/User_Service
spring.datasource.username=postgres
spring.datasource.password=Suchandra77@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
